FROM python:3.11-slim

WORKDIR /app

# 環境変数を設定して、Pythonの出力をバッファリングせずリアルタイムで表示させます
ENV PYTHONUNBUFFERED=1

# 依存ライブラリのインストール
RUN pip install --no-cache-dir redis

# SDKとモニタープログラムのコピー
# 基準点（MUFフォルダ）から見た相対パスを指定します
COPY ./muf /app/muf
COPY monitor/monitor.py /app/monitor.py

CMD ["python", "monitor.py"]